### ISSUE TITLE
如何设置表头背景色

### ISSUE THREAD

**Issue by zl7261** [livelyPeng/pl-table#13]
headerRowClassName函数指定的class依然没有覆盖默认的element table 样式 
需要通过/deep/来修改表头样式
主要是 background-color 与color样式
```html
<pl-table   headerRowClassName="haha"></pl-table>
<style>
  .haha {
        background-color: rgb(0, 51, 102) !important;
        color: red;
        text-align: center
    }

</style>
```

color成功修改,但bg-color只修改了最右边的背景,子类的<td>的没有没修改
```html
<table><thead><tr class='haha'><th>
```

真正修改表头的背景颜色,需要
```css
 /deep/ .plTableBox .el-table th {
        color: #fff;
        background-color: rgb(0, 51, 102);
    }
```
element有对应的表头属性可以设置 
header-cell-style="{'background': 'rgb(0, 51, 102)', 'color': '#fff'}"
